# scrutinizer-ci.com configuration
imports:
    - javascript
    - python
filter:
    excluded_paths: [weblate/media/js/jquery*, weblate/media/js/mousetrap*, weblate/media/bootstrap/js/*, weblate/html/js/*, docs/*, weblate/trans/south_migrations/*, weblate/accounts/south_migrations/*, weblate/lang/south_migrations/*]
