language: python
python:
  - "2.7"
env:
  matrix:
    - DJANGO_VERSION=1.5.5 TRAVIS_DATABASE=sqlite TRAVIS_RUN_TESTS="trans lang accounts"
    - DJANGO_VERSION=1.6 TRAVIS_DATABASE=mysql TRAVIS_RUN_TESTS="weblate.trans weblate.lang weblate.accounts"
    - DJANGO_VERSION=1.6 TRAVIS_DATABASE=postgresql TRAVIS_RUN_TESTS="weblate.trans weblate.lang weblate.accounts"
    - DJANGO_VERSION=1.6 TRAVIS_DATABASE=sqlite TRAVIS_RUN_TESTS="weblate.trans weblate.lang weblate.accounts"
#  global:
# Sauce labs setup
#    - secure: "W4EtqCQSbSWb2sDwHd0obttzUTKIPyFZE90qD+YdV76YLgIK7QX4Vc6Hx9fRRNy397h4RrYIzyU2vemGIR5j8cR16Y6MyJ8Fy4DyC2mHyo3T7Tx4/cJYTQDPF2G4kxjR+vmhsdQIdmaYLsjtb2C2M0aIkU8FGFv6D3+TXqsoOmI="
#    - secure: "AYu5aeoSHEbBA67Y60yhVa5B/3a7ZLvECnGvyKGfH4oJU/yeEBokgiqFzwRAcXWILMVSMTVGw3vpcq3B/5SRg1vuq+OzRzZ/kopwd4z7P91MYNeXgKNC0bIgEyKg0Fb3ElK1XjFlAXLlIZTwhVBwuJSX+EUFluecN8kJ7Cf7yjE="
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install git libffi-dev libpq-dev libmysqlclient-dev libicu-dev
# commands to install dependencies
install: 
  - pip install --use-mirrors Django==$DJANGO_VERSION
  - pip install --use-mirrors -r requirements.txt
  - pip install --use-mirrors -r requirements-optional.txt
  - pip install --use-mirrors -r requirements-test.txt
# generate configuration and create databases
before_script:
  - mysql -e 'create database weblate;'
  - psql -c 'create database weblate;' -U postgres
#  - curl https://gist.github.com/santiycr/5139565/raw/sauce_connect_setup.sh | bash
# commands to run tests
script: 
  - ./scripts/generate-locales
  - ./manage.py validate --settings weblate.settings_test
  - ./manage.py syncdb --noinput --settings weblate.settings_test
  - ./manage.py migrate --settings weblate.settings_test --traceback
  - coverage run --source=. ./manage.py test --settings weblate.settings_test $TRAVIS_RUN_TESTS 
  - pep8 --exclude migrations weblate
  - pylint --reports=n --rcfile=pylint.rc weblate
after_success:
  - coveralls
